### ISSUE TITLE
Uses voxelIndex to compare between previous matched position and current position

### ISSUE THREAD

**Issue by nakedible** [max-mapper/voxel-highlight#4]
It seems that voxels.voxelIndex result is stored and compared against to determine if the hit voxel is the same or a different one. However, voxelIndex is relative to the chunk, so this comparison fails if hitting the exact same voxel in another chunk (quite unlikely). However, the bigger crime is that there's a direct dependency to the voxelIndex function.

The implementation should just store and compare voxel positions.

**Comment by theoxylo** [comment]
yes, it is an "optimization". I suppose we could construct a cache key string based on position similar to that used for chunks, something like "15|-10|237"

**Comment by theoxylo** [comment]
changed to position string cache key in pull request

**Comment by nakedible** [comment]
I really don't understand the "optimization" to use a cache key string. http://jsperf.com/vector-vs-string

What's wrong with just storing the position vector and comparing each component? This reduces to a monomorphic test for a hidden class + three comparisons with simple linear object field offsets.

**Comment by theoxylo** [comment]
sometimes it is nice to have a single-valued (non-array), human readable cache key. but I guess we don't need that here

**Comment by nakedible** [comment]
True, from a programming point of view, that would be nicer.

But in any case, voxelIndex is no longer being used, so this issue is no longer relevant.
